application: kick-saver
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: static/favicon.png
  upload: static/favicon\.png

- url: /static
  static_dir: static

- url: /crawl
  script: kickparser.py
  login: admin

- url: /tweet
  script: twitter.py
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
